---
- hosts: all
  become: true
  tasks:
    - name: Install java
      apt:
        name:
          - wget
          - openjdk-8-jdk

    - name: Download jenkins.repo
      apt_repository:
        repo: deb http://pkg.jenkins.io/debian-stable binary/
    - name: Import Jenkins Key
      apt_key:
        state: present
        key: https://pkg.jenkins.io/debian/jenkins.io.key

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start & Enable Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: true

    - name: Sleep for 30 seconds and continue with play
      wait_for: timeout=30

    - name: Get init password Jenkins
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      changed_when: false
      register: result

    - name: Print init password Jenkins
      debug:
        var: result.stdout
